### ISSUE TITLE
sqlAlchemy > 2.0 not working

### ISSUE THREAD

**Issue by Jopie01** [iredmail/iRedAPD#15]
I did a `pip install sqlalchemy` which installed sqlAlchemy 2.0.15 but using this version, I got a lot of errors like `Error while executing SQL command: ObjectNotExecutableError()` or `AttributeError("'Engine' object has no attribute 'execute'")`. Searching the internet I came across https://stackoverflow.com/questions/69490450/objectnotexecutableerror-when-executing-any-sql-query-using-asyncengine which is not direct related, but I downgraded to the latest 1.4 version and now it works.

**Comment by zod076** [comment]
I've the same issue but with version 1.0.14 on FreeBSD 14

# pkg info py310-sqlalchemy10-1.0.14 
py310-sqlalchemy10-1.0.14
Name           : py310-sqlalchemy10
Version        : 1.0.14
Installed on   : Thu Feb 29 23:36:02 2024 +08
Origin         : databases/py-sqlalchemy10
Architecture   : FreeBSD:14:amd64
Prefix         : /usr/local
Categories     : python databases
Licenses       : MIT
Maintainer     : m.tsatsenko@gmail.com
WWW            : https://www.sqlalchemy.org/
Comment        : Python SQL toolkit and Object Relational Mapper 1.0.x
Options        :
        DOCS           : off
        EXAMPLES       : off
        MSSQL          : off
        PGSQL          : off
        SQLITE         : on
Annotations    :
        FreeBSD_version: 1400097
        cpe            : cpe:2.3:a:sqlalchemy:sqlalchemy:1.0.14:::::freebsd14:x64
        flavor         : py310
Flat size      : 9.91MiB
Description    :
The Python SQL Toolkit and Object Relational Mapper

# python3 -V                        
Python 3.10.13

# python3 /opt/iredapd/iredapd.py
/opt/iredapd/iredapd.py:6: DeprecationWarning: The asyncore module is deprecated and will be removed in Python 3.12. The recommended replacement is asyncio
  import asyncore
Traceback (most recent call last):
  File "/opt/iredapd/iredapd.py", line 20, in <module>
    from libs import __version__, daemon, utils
  File "/opt/iRedAPD-5.3.3/libs/utils.py", line 18, in <module>
    from sqlalchemy import create_engine
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/__init__.py", line 9, in <module>
    from .sql import (
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/__init__.py", line 8, in <module>
    from .expression import (
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/expression.py", line 31, in <module>
    from .functions import func, modifier, FunctionElement, Function
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/functions.py", line 11, in <module>
    from . import sqltypes, schema
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 16, in <module>
    from .elements import quoted_name, type_coerce, _defer_name
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 21, in <module>
    from .base import Executable, PARSE_AUTOCOMMIT, Immutable, NO_ARG
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 49, in <module>
    class _DialectArgView(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by iredmail** [comment]
Dear all,

We have no plan to fix this shortly since iRedAPD works fine with SQLAlchemy-1.4.x which is available in ports tree (databases/py-sqlalchem14). The final solution will be replacing iRedAPD with a milter program written in Golang for better performance. FYI https://github.com/iredmail/iRedAPD/issues/11
